-- 코드를 입력하세요
SELECT YEAR(b.SALES_DATE) as YEAR, MONTH(b.SALES_DATE) as MONTH, a.GENDER AS GENDER, count(DISTINCT a.USER_ID) AS USER
FROM USER_INFO a
JOIN ONLINE_SALE b
USING (USER_ID)
WHERE a.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, a.GENDER
ORDER BY 1, 2, 3;