-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, p.PRICE * SUM(o.AMOUNT) as TOTAL_SALES
FROM  FOOD_ORDER as o
INNER JOIN FOOD_PRODUCT as p USING(PRODUCT_ID)
WHERE o.PRODUCE_DATE LIKE '2022-05%'
GROUP BY o.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;