# -- 코드를 입력하세요
# SELECT USER_ID, NICKNAME, TOTAL_PRICE
# FROM USED_GOODS_USER
# JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE
#     FROM USED_GOODS_BOARD
#     GROUP BY WRITER_ID,STATUS
#     HAVING STATUS = 'DONE'
#     AND SUM(PRICE) >= 700000) B
# ON B.WRITER_ID = USER_ID
# ORDER BY TOTAL_PRICE;

SELECT USER_ID, NICKNAME, TOTAL_PRICE
FROM USED_GOODS_USER
JOIN (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID,STATUS
    HAVING STATUS = 'DONE'
    AND SUM(PRICE) >= 700000) B
ON B.WRITER_ID = USER_ID
ORDER BY TOTAL_PRICE;