SELECT d.DEPT_ID, d.DEPT_NAME_EN, AVG_SAL
FROM HR_DEPARTMENT as d
    JOIN (
        SELECT DEPT_ID, ROUND(AVG(SAL),0) as AVG_SAL
        FROM HR_EMPLOYEES
        GROUP BY DEPT_ID
    ) as e on d.DEPT_ID = e.DEPT_ID
ORDER BY 3 DESC;