# 조건에 맞는 회원수 구하기
SELECT COUNT(USER_ID) as USERS
FROM USER_INFO
WHERE (JOINED like '2021-%') & (AGE like '2%')

-- WHERE
    JOINED <= '2021-12-31' AND AGE BETWEEN 20 AND 29

-- WHERE TO_CHAR(JOINED, 'YYYY') = 2021
   AND AGE >= 20
   AND AGE <= 29
   ;