# 과일로 만든 아이스크림 만들기
# 테이블: FISRT_HALF, ICECREAM_INFO
SELECT FI.FLAVOR
  FROM FIRST_HALF FI, ICECREAM_INFO IC
  WHERE FI.FLAVOR = IC.FLAVOR AND FI.TOTAL_ORDER > 3000 AND IC.INGREDIENT_TYPE = 'fruit_based'
  ORDER BY TOTAL_ORDER DESC