# 조건에 맞는 개발자 찾기
# MySQL (BITWISE & 연산자를 이용한)
SELECT DISTINCT a.ID, a.EMAIL, a.FIRST_NAME, a.LAST_NAME
FROM DEVELOPERS a, SKILLCODES b
WHERE 
    (a.SKILL_CODE & b.CODE) > 0
    AND b.NAME IN ("Python", "C#")
ORDER BY a.ID;


SELECT  DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM    DEVELOPERS D, SKILLCODES S
WHERE   (D.SKILL_CODE & S.CODE )>0 AND S.NAME REGEXP 'Python|C#'
ORDER BY D.ID;