SELECT ROUND(SUM(IFNULL(LENGTH, 10)) / COUNT(IFNULL(LENGTH, 10)),2) as AVERAGE_LENGTH
FROM FISH_INFO

SELECT ROUND(
AVG(
CASE
WHEN LENGTH IS NULL THEN 10
ELSE LENGTH
END
),
2
) AS AVERAGELENGTH
FROM FISHINFO;

SELECT
    ROUND(AVG(IFNULL(LENGTH, 10)), 2) AVERAGE_LENGTH
FROM
    FISH_INFO