#
SELECT
    ID
    , EMAIL
    , FIRST_NAME
    , LAST_NAME
FROM
    DEVELOPER_INFOS
WHERE
    CONCAT_WS(', ', SKILL_1, SKILL_2, SKILL_3) REGEXP 'Python'
ORDER BY
    ID;

---------------------
SELECT  ID, EMAIL, FIRST_NAME, LAST_NAME
FROM    DEVELOPER_INFOS
WHERE   'Python' in (SKILL_1, SKILL_2, SKILL_3)
ORDER BY 1 asc;