-- 코드를 입력하세요
# SELECT CATEGORY, PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY) AND CATEGORY IN ('과자','국','김치','식용유')
# ORDER BY PRICE DESC

SELECT a.CATEGORY, a.PRICE as MAX_PRICE, a.PRODUCT_NAME
FROM FOOD_PRODUCT a
LEFT JOIN FOOD_PRODUCT b
ON a.CATEGORY = b.CATEGORY AND a.PRICE < b.PRICE
WHERE b.CATEGORY IS NULL AND a.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY 2 desc;