WITH GROUP_DEVELOPERS AS (
    SELECT ID, EMAIL, GROUP_CONCAT(DISTINCT NAME, CATEGORY) AS GROUPED
    FROM SKILLCODES
        JOIN DEVELOPERS
        ON DEVELOPERS.SKILL_CODE & SKILLCODES.CODE
    GROUP BY 1,2
)

SELECT 
    CASE
        WHEN GROUPED LIKE '%Front%' AND GROUPED LIKE '%Python%' THEN 'A'
        WHEN GROUPED LIKE '%C#%' THEN 'B' 
        WHEN GROUPED LIKE '%Front%' THEN 'C'
    END AS GRADE, 
    ID, EMAIL
FROM GROUP_DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;